#!/usr/bin/env bash
# Bash script that gives you information about the school file

filename="school"
if [ -e $filename ]
then
    echo "$filename file exists"
    if [ -s $filename ]
    then
        echo "$filename file is not empty" 
    else
        echo "$filename file is empty"
    if [ -f $filename ]
    then
        echo "$filename is a regular file"
else
    echo "$filename file does not exist"
fi
